CREATE OR REPLACE ROLE developer;

CREATE OR REPLACE WAREHOUSE SPOK_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'ECONOMY';
GRANT ALL PRIVILEGES ON WAREHOUSE spok_wh TO developer;

CREATE OR REPLACE DATABASE CORE_DWH;
GRANT OWNERSHIP ON DATABASE CORE_DWH to developer;
GRANT ALL PRIVILEGES ON DATABASE CORE_DWH TO developer;

CREATE OR REPLACE USER karolk IDENTIFIED BY 'xxxx';


GRANT ROLE spokdeveloper TO USER karolk;

ALTER USER karolk SET default_role = developer;
